services:
  - type: worker
    name: crypto-monitor
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/worker.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
    autoDeploy: true